# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoping', '0090_auto_20170426_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.IntegerField()),
                ('term', models.IntegerField()),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DocTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('scaled_score', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
        migrations.CreateModel(
            name='HDocTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('score', models.FloatField(null=True)),
                ('run_id', models.IntegerField(db_index=True, null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
        migrations.CreateModel(
            name='HTopic',
            fields=[
                ('topic', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, null=True)),
                ('n_docs', models.IntegerField(null=True)),
                ('n_words', models.IntegerField(null=True)),
                ('scale', models.FloatField(null=True)),
                ('run_id', models.IntegerField(db_index=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic')),
            ],
        ),
        migrations.CreateModel(
            name='HTopicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('run_id', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTopicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PY', models.IntegerField()),
                ('score', models.FloatField()),
                ('count', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic')),
            ],
        ),
        migrations.CreateModel(
            name='RunStats',
            fields=[
                ('run_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('batch_count', models.IntegerField()),
                ('last_update', models.DateTimeField()),
                ('topic_titles_current', models.NullBooleanField()),
                ('topic_scores_current', models.NullBooleanField()),
                ('topic_year_scores_current', models.NullBooleanField()),
                ('docs_seen', models.IntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('method', models.CharField(choices=[('LD', 'lda'), ('HL', 'hlda'), ('DT', 'dtm'), ('NM', 'nmf')], default='LD', max_length=2)),
                ('error', models.FloatField(null=True)),
                ('errortype', models.TextField(null=True)),
                ('iterations', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('doc_topic_score_threshold', models.FloatField()),
                ('doc_topic_scaled_score', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('run_id', models.ManyToManyField(to='tmv_app.RunStats')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('score', models.FloatField(null=True)),
                ('run_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topiccorr', models.IntegerField()),
                ('score', models.FloatField(null=True)),
                ('run_id', models.IntegerField(db_index=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Term')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PY', models.IntegerField()),
                ('score', models.FloatField()),
                ('count', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='htopicterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Term'),
        ),
        migrations.AddField(
            model_name='htopicterm',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic'),
        ),
        migrations.AddField(
            model_name='hdoctopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic'),
        ),
        migrations.AddField(
            model_name='doctopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic'),
        ),
    ]
