# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='max_features',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='runstats',
            name='ngram',
            field=models.IntegerField(null=True),
        ),
    ]
