# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tmv_app.Doc'),
        ),
    ]
