# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='term',
            name='id',
        ),
        migrations.AddField(
            model_name='doc',
            name='doc',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='term',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
