# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='topic_titles_current',
            field=models.NullBooleanField(),
        ),
    ]
