# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0002_auto_20170427_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
