# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0002_auto_20161103_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='docs_seen',
            field=models.IntegerField(null=True),
        ),
    ]
