# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0003_runstats_docs_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='PY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
