# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0003_docauthors_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctopic',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Doc'),
        ),
    ]
