# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0003_auto_20170504_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.RunStats'),
        ),
    ]
