# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0004_auto_20161121_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
