# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0004_term_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
