# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0005_auto_20161121_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='modkey',
            field=models.IntegerField(null=True),
        ),
    ]
