# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0006_auto_20161024_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
