# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0006_doc_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='UT',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
