# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-26 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0006_auto_20170523_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
