# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0006_doc_modkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='modkey',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
