# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0007_auto_20161121_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
