# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0007_topic_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='topic_scores_current',
            field=models.NullBooleanField(),
        ),
    ]
