# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0007_topic_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccorr',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
