# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0007_doc_ut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UT', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
