# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0008_topiccorr_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccorr',
            name='year',
        ),
        migrations.AddField(
            model_name='topiccorr',
            name='ar',
            field=models.IntegerField(default=-1),
        ),
    ]
