# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0008_docauthors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docauthors',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
