# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0008_runstats_topic_scores_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PY', models.IntegerField()),
                ('score', models.FloatField()),
                ('count', models.FloatField()),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='runstats',
            name='topic_year_scores_current',
            field=models.NullBooleanField(),
        ),
    ]
