# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0009_runstats_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDocTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Doc')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='HTopic',
            fields=[
                ('topic', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('n_docs', models.IntegerField()),
                ('n_words', models.IntegerField()),
                ('scale', models.FloatField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic')),
            ],
        ),
        migrations.CreateModel(
            name='HTopicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Term')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
    ]
