# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0009_auto_20161026_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runstats',
            name='id',
        ),
        migrations.AddField(
            model_name='doc',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docauthors',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctopic',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runstats',
            name='run_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='run_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicterm',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicyear',
            name='run_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
