# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0009_auto_20161018_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='PY',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
