# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0009_auto_20170602_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
