# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0010_topic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('score', models.FloatField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.RunStats')),
            ],
        ),
        migrations.CreateModel(
            name='TopicDTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('dynamictopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
    ]
