# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0010_auto_20161028_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
