# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0011_auto_20161028_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
