# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0011_auto_20161201_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='htopic',
            name='run_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
