# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0011_dynamictopic_topicdtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictopic',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
