# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0012_htopic_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdoctopic',
            name='run_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='htopicterm',
            name='run_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
