# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0012_auto_20161028_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='doc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
