# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0012_auto_20170606_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='primary_dtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic'),
        ),
    ]
