# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0013_auto_20161201_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdoctopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic'),
        ),
        migrations.AlterField(
            model_name='htopicterm',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic'),
        ),
    ]
