# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 14:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0014_dynamictopicterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='top_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
