# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0014_auto_20161201_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdoctopic',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
