# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0104_profile'),
        ('tmv_app', '0015_topic_top_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicARScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('ar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.AR')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
    ]
