# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0015_hdoctopic_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTopicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PY', models.IntegerField()),
                ('score', models.FloatField()),
                ('count', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.HTopic')),
            ],
        ),
    ]
