# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0016_topicarscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicarscores',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
