# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0017_auto_20161229_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='error',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='runstats',
            name='errortype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='runstats',
            name='iterations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='method',
            field=models.CharField(choices=[('LD', 'lda'), ('HL', 'hlda'), ('DT', 'dtm'), ('NM', 'nmf')], default='LD', max_length=2),
        ),
    ]
