# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0017_auto_20170608_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicterm',
            name='PY',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
