# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0018_topicterm_py'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='term_count',
            field=models.IntegerField(null=True),
        ),
    ]
