# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0019_runstats_term_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='growth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='method',
            field=models.CharField(choices=[('LD', 'lda'), ('HL', 'hlda'), ('DT', 'dtm'), ('NM', 'nmf'), ('BD', 'BleiDTM')], default='LD', max_length=2),
        ),
    ]
