# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-19 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0020_auto_20170616_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='dthreshold',
            field=models.FloatField(null=True),
        ),
    ]
