# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0021_runstats_dthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='error',
            field=models.FloatField(default=0, null=True),
        ),
    ]
