# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0024_runstats_max_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='primary_dtopic',
        ),
        migrations.AddField(
            model_name='topic',
            name='primary_dtopic',
            field=models.ManyToManyField(null=True, to='tmv_app.DynamicTopic'),
        ),
    ]
