# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 12:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0025_auto_20170807_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopic',
            name='top_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='topic',
            name='primary_dtopic',
            field=models.ManyToManyField(to='tmv_app.DynamicTopic'),
        ),
    ]
