# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0027_dynamictopicterm_py'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTopicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PY', models.IntegerField()),
                ('score', models.FloatField(null=True)),
                ('count', models.FloatField(null=True)),
                ('run_id', models.IntegerField(db_index=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic')),
            ],
        ),
    ]
