# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0029_auto_20170818_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictopicterm',
            name='l1ys',
        ),
        migrations.RemoveField(
            model_name='dynamictopicterm',
            name='l5ys',
        ),
        migrations.AddField(
            model_name='dynamictopic',
            name='l1ys',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dynamictopic',
            name='l5ys',
            field=models.IntegerField(null=True),
        ),
    ]
