# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0030_auto_20170818_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictopic',
            name='l1ys',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dynamictopic',
            name='l5ys',
            field=models.FloatField(null=True),
        ),
    ]
