# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0031_auto_20170818_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopicyear',
            name='year_share',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='topicyear',
            name='year_share',
            field=models.FloatField(null=True),
        ),
    ]
