# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0032_auto_20170818_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='primary_wg',
            field=models.IntegerField(null=True),
        ),
    ]
