# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0034_topic_wg_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='process_id',
            field=models.IntegerField(null=True),
        ),
    ]
