# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0036_runstats_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='dthreshold',
            field=models.FloatField(default=0.0005),
        ),
    ]
