# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0037_auto_20171016_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='wg_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='wg_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='wg_3',
            field=models.FloatField(null=True),
        ),
    ]
