# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0159_auto_20171020_1327'),
        ('tmv_app', '0038_auto_20171016_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTopic_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('scaled_score', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_2')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
    ]
