# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0039_doctopic_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='K',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='runstats',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='runstats',
            name='max_iterations',
            field=models.IntegerField(null=True),
        ),
    ]
