# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0040_auto_20171023_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='alpha',
            field=models.FloatField(default=0.01, null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='max_iterations',
            field=models.IntegerField(default=200, null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='ngram',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
