# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0041_auto_20171023_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='K',
            field=models.IntegerField(help_text='Number of topics', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='alpha',
            field=models.FloatField(default=0.01, help_text='Alpha parameter', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='limit',
            field=models.IntegerField(default=0, help_text='Limit model to first x documents (leave as zero for no limit)', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='max_features',
            field=models.IntegerField(help_text='Maximum number of terms', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='max_iterations',
            field=models.IntegerField(default=200, help_text='Maximum iterations', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='ngram',
            field=models.IntegerField(default=1, help_text='Length of feature n_gram', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='run_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
