# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0042_auto_20171023_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='batch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='topic_scores_current',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='topic_titles_current',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='topic_year_scores_current',
            field=models.NullBooleanField(default=False),
        ),
    ]
