# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0043_auto_20171023_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Interrupted'), (3, 'Finished')], default=0),
        ),
    ]
