# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0044_runstats_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctopic',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='doctopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='hdoctopic',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='hdoctopic',
            name='topic',
        ),
        migrations.DeleteModel(
            name='DocTopic',
        ),
        migrations.DeleteModel(
            name='HDocTopic',
        ),
    ]
