# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0045_auto_20171025_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocTopic_copy',
            new_name='DocTopic',
        ),
    ]
