# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0046_auto_20171025_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='db_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='runstats',
            name='nmf_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='runstats',
            name='tfidf_time',
            field=models.FloatField(default=0),
        ),
    ]
