# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0048_auto_20171102_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicyear',
            name='count',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='topicyear',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
