# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0049_auto_20171103_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicarscores',
            name='pgrowth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='topicarscores',
            name='pgrowthn',
            field=models.FloatField(null=True),
        ),
    ]
