# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0052_topic_ipcc_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='db',
            field=models.BooleanField(default=True),
        ),
    ]
