# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0053_runstats_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='db',
            field=models.BooleanField(default=True, help_text='Record the results into the database? Or just run the model and record statistics?'),
        ),
    ]
