# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0054_auto_20171115_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='empty_topics',
            field=models.IntegerField(null=True),
        ),
    ]
