# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0056_auto_20171205_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedoctotal',
            name='period',
        ),
        migrations.RemoveField(
            model_name='timedoctotal',
            name='run',
        ),
        migrations.RemoveField(
            model_name='timedtopic',
            name='dtopic',
        ),
        migrations.RemoveField(
            model_name='timedtopic',
            name='period',
        ),
        migrations.DeleteModel(
            name='TimeDocTotal',
        ),
        migrations.DeleteModel(
            name='TimeDTopic',
        ),
        migrations.DeleteModel(
            name='TimePeriod',
        ),
    ]
