# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0058_auto_20171205_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.TimePeriod'),
        ),
    ]
