# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0060_runstats_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='periods',
            field=models.ManyToManyField(to='tmv_app.TimePeriod'),
        ),
    ]
