# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0061_auto_20171205_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedoctotal',
            name='dt_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='timedoctotal',
            name='n_docs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timedtopic',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
