# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0062_auto_20171206_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='max_features',
            field=models.IntegerField(default=0, help_text='Maximum number of terms (0 = no limit)'),
        ),
    ]
