# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0064_timedtopic_year_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictopicyear',
            name='topic',
        ),
        migrations.AlterField(
            model_name='timedtopic',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='timedtopic',
            name='year_share',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DynamicTopicYear',
        ),
    ]
