# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0065_auto_20171219_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopic',
            name='wg_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dynamictopic',
            name='wg_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dynamictopic',
            name='wg_3',
            field=models.FloatField(null=True),
        ),
    ]
