# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0066_auto_20171229_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopic',
            name='ipcc_coverage',
            field=models.FloatField(null=True),
        ),
    ]
