# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0068_dynamictopic_primary_wg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTopicCorr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('ar', models.IntegerField(default=-1)),
                ('run_id', models.IntegerField(db_index=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic')),
                ('topiccorr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topiccorr', to='tmv_app.DynamicTopic')),
            ],
        ),
    ]
