# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0183_emailtokens_project'),
        ('tmv_app', '0069_dynamictopiccorr'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTopicARScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('share', models.FloatField(null=True)),
                ('pgrowth', models.FloatField(null=True)),
                ('pgrowthn', models.FloatField(null=True)),
                ('ar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.AR')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
    ]
