# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0070_dynamictopicarscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictopicarscores',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic'),
        ),
    ]
