# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0073_auto_20180109_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopic',
            name='wg_prop',
            field=models.FloatField(null=True),
        ),
    ]
