# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0075_runstats_fulltext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runstats',
            old_name='fullText',
            new_name='fulltext',
        ),
    ]
