# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0076_auto_20180123_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='coherence',
            field=models.FloatField(null=True),
        ),
    ]
