# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0077_runstats_coherence'),
    ]

    operations = [
        migrations.CreateModel(
            name='KFold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K', models.IntegerField()),
                ('error', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.RunStats')),
            ],
        ),
    ]
