# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0078_kfold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kfold',
            name='error',
            field=models.FloatField(null=True),
        ),
    ]
