# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0079_auto_20180126_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedtopic',
            name='pgrowth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='timedtopic',
            name='pgrowthn',
            field=models.FloatField(null=True),
        ),
    ]
