# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0081_auto_20180216_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopic',
            name='ipcc_time_score',
            field=models.FloatField(null=True),
        ),
    ]
