# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0082_dynamictopic_ipcc_time_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timedtopic',
            old_name='year_share',
            new_name='share',
        ),
        migrations.RenameField(
            model_name='topicyear',
            old_name='year_share',
            new_name='share',
        ),
        migrations.AddField(
            model_name='timedtopic',
            name='ipcc_coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='timedtopic',
            name='ipcc_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='timedtopic',
            name='ipcc_share',
            field=models.FloatField(null=True),
        ),
    ]
