# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0086_termpolarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='termpolarity',
            name='POS',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='termpolarity',
            name='polarity',
            field=models.FloatField(null=True),
        ),
    ]
