# Generated by Django 2.0.5 on 2018-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0087_auto_20180327_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='citations',
            field=models.BooleanField(default=False, help_text='scale term scores by citations?'),
        ),
    ]
