# Generated by Django 2.0.5 on 2018-09-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0036_auto_20180904_1237'),
        ('tmv_app', '0088_runstats_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctopic',
            name='ut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Utterance'),
        ),
    ]
