# Generated by Django 2.0.5 on 2018-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0088_runstats_citations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='size',
        ),
        migrations.AddField(
            model_name='topic',
            name='share',
            field=models.FloatField(null=True),
        ),
    ]
