# Generated by Django 2.0.5 on 2018-07-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0209_auto_20180704_1801'),
        ('tmv_app', '0089_auto_20180703_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocDynamicTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic')),
            ],
        ),
    ]
