# Generated by Django 2.0.5 on 2018-10-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0089_doctopic_ut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTopicTimePeriodScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('share', models.FloatField(null=True)),
                ('pgrowth', models.FloatField(null=True)),
                ('pgrowthn', models.FloatField(null=True)),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.TimePeriod')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.DynamicTopic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTimePeriodScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('share', models.FloatField(null=True)),
                ('pgrowth', models.FloatField(null=True)),
                ('pgrowthn', models.FloatField(null=True)),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.TimePeriod')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
            ],
        ),
        migrations.AlterField(
            model_name='runstats',
            name='method',
            field=models.CharField(choices=[('LD', 'lda'), ('HL', 'hlda'), ('DT', 'dnmf'), ('NM', 'nmf'), ('BD', 'BleiDTM')], default='LD', max_length=2),
        ),
    ]
