# Generated by Django 2.0.5 on 2018-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0090_auto_20181019_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
