# Generated by Django 2.0.5 on 2018-10-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0091_auto_20181019_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictopiccorr',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.TimePeriod'),
        ),
        migrations.AddField(
            model_name='topiccorr',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.TimePeriod'),
        ),
    ]
