# Generated by Django 2.0.5 on 2018-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0091_auto_20181016_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='fancy_tokenization',
            field=models.BooleanField(default=False, help_text='tokenize so that multiple word keywords remain whole'),
        ),
    ]
