# Generated by Django 2.0.5 on 2018-10-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0092_runstats_fancy_tokenization'),
        ('tmv_app', '0092_auto_20181021_1405'),
    ]

    operations = [
    ]
