# Generated by Django 2.1.2 on 2018-10-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0092_runstats_fancy_tokenization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runstats',
            old_name='dthreshold',
            new_name='dt_threshold',
        ),
        migrations.AddField(
            model_name='runstats',
            name='doc_topic_scaled_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runstats',
            name='dt_threshold_scaled',
            field=models.FloatField(default=0.01),
        ),
    ]
