# Generated by Django 2.1.2 on 2018-10-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0093_auto_20181029_1233'),
        ('tmv_app', '0093_merge_20181026_1551'),
    ]

    operations = [
    ]
