# Generated by Django 2.1.2 on 2018-10-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0094_merge_20181030_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='method',
            field=models.CharField(choices=[('LD', 'lda'), ('HL', 'hlda'), ('DT', 'dnmf'), ('NM', 'nmf'), ('BD', 'BleiDTM')], default='NM', max_length=2),
        ),
    ]
