# Generated by Django 2.1.2 on 2019-01-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0095_auto_20181030_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runstats',
            old_name='max_iterations',
            new_name='max_iter',
        ),
    ]
