# Generated by Django 2.1.2 on 2018-10-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0094_merge_20181029_1509'),
        ('tmv_app', '0095_auto_20181030_1615'),
    ]

    operations = [
    ]
