# Generated by Django 2.1.2 on 2019-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0096_auto_20190122_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='alpha',
            field=models.FloatField(default=0.01, help_text='Alpha parameter (try higher values in LDA, including > 1). Low (high) values indicate that documents should be composed of few (many) topics.', null=True),
        ),
    ]
