# Generated by Django 2.1.2 on 2019-02-11 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0098_timeperiod_parlperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='ys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
