# Generated by Django 2.1.2 on 2019-03-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0099_auto_20190211_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='top_chain_var',
            field=models.FloatField(default=0.05, help_text='Chain var parameter for dtm', null=True),
        ),
    ]
