# Generated by Django 2.1.2 on 2019-02-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0096_merge_20181031_1727'),
        ('tmv_app', '0099_auto_20190211_1429'),
    ]

    operations = [
    ]
