# Generated by Django 2.1.2 on 2019-03-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tmv_app', '0100_runstats_top_chain_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordIntrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('intruded_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intruding_topic', to='tmv_app.Term')),
                ('real_words', models.ManyToManyField(to='tmv_app.Term')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
