# Generated by Django 2.1.2 on 2019-03-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0100_merge_20190220_1405'),
        ('tmv_app', '0102_topicintrusion'),
    ]

    operations = [
    ]
