# Generated by Django 2.1.2 on 2019-03-20 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0103_merge_20190320_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='extra_stopwords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='runstats',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
