# Generated by Django 2.1.2 on 2019-03-21 15:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0104_auto_20190320_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocTerm',
        ),
        migrations.AlterField(
            model_name='runstats',
            name='extra_stopwords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='list of stopwords that are used additionally to the standard ones', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='language',
            field=models.TextField(help_text='language of the documents that have been analyzed (also used for stopword identification)', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='psearch',
            field=models.ForeignKey(help_text='relation to the parliamentary search object', null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Search'),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='query',
            field=models.ForeignKey(help_text='relation to the scoping search object', null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Query'),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Interrupted'), (3, 'Finished')], default=0, help_text='status of the model execution'),
        ),
        migrations.AlterField(
            model_name='termpolarity',
            name='POS',
            field=models.TextField(null=True, verbose_name='part of speech'),
        ),
    ]
