# Generated by Django 2.1.2 on 2019-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0105_auto_20190321_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='exclusivity',
            field=models.TextField(null=True),
        ),
    ]
