# Generated by Django 2.1.2 on 2019-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0106_runstats_exclusivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='rng_seed',
            field=models.IntegerField(default=1, help_text='seed for random number generator for stochastic estimation of topic model (blei dtm)', null=True),
        ),
    ]
