# Generated by Django 2.1.2 on 2019-04-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0108_auto_20190329_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='runtime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='docdynamictopic',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.Doc'),
        ),
        migrations.AlterField(
            model_name='doctopic',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.Doc'),
        ),
        migrations.AlterField(
            model_name='doctopic',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Paragraph'),
        ),
        migrations.AlterField(
            model_name='doctopic',
            name='ut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Utterance'),
        ),
        migrations.AlterField(
            model_name='dynamictopicarscores',
            name='ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.AR'),
        ),
        migrations.AlterField(
            model_name='dynamictopiccorr',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='dynamictopicterm',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.Term'),
        ),
        migrations.AlterField(
            model_name='dynamictopictimeperiodscores',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='timedoctotal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmv_app.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='timedtopic',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tmv_app.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='timeperiod',
            name='parlperiod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.ParlPeriod'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='topiccorr',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.TimePeriod'),
        ),
        migrations.AlterField(
            model_name='topicterm',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.Term'),
        ),
        migrations.AlterField(
            model_name='topictimeperiodscores',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmv_app.TimePeriod'),
        ),
    ]
