# Generated by Django 2.1.7 on 2019-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0109_auto_20190415_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ipcc_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='ipcc_share',
            field=models.FloatField(null=True),
        ),
    ]
