# Generated by Django 2.1.7 on 2019-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0110_auto_20190417_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicterm',
            name='alltopic_score',
            field=models.FloatField(null=True),
        ),
    ]
