# Generated by Django 2.2 on 2019-05-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0111_topicterm_alltopic_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='exclusivity',
            field=models.FloatField(null=True),
        ),
    ]
