# Generated by Django 2.2 on 2019-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0113_auto_20190508_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='manual_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
