# Generated by Django 2.2 on 2019-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0114_topic_manual_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='original_title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
