# Generated by Django 2.2 on 2019-06-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0115_topic_original_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='lda_learning_method',
            field=models.IntegerField(choices=[('on', 'Online'), ('ba', 'Batch')], null=True),
        ),
    ]
