# Generated by Django 2.2 on 2019-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0116_runstats_lda_learning_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='lda_learning_method',
            field=models.CharField(choices=[('on', 'Online'), ('ba', 'Batch')], default='ba', max_length=2, null=True),
        ),
    ]
