# Generated by Django 2.2 on 2019-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0117_auto_20190618_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='runstats',
            name='lda_library',
            field=models.CharField(choices=[('sk', 'Sklearn'), ('ld', 'lda')], default='sk', max_length=2, null=True),
        ),
    ]
