# Generated by Django 2.2 on 2019-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0118_runstats_lda_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='lda_learning_method',
            field=models.CharField(choices=[('on', 'Online'), ('ba', 'Batch')], default='ba', help_text='When using LDA in sklearn, you can choose between batch or online learning', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='lda_library',
            field=models.CharField(choices=[('sk', 'Sklearn'), ('ld', 'lda')], default='sk', help_text='you can use sklearn or https://github.com/lda-project/lda for LDA', max_length=2, null=True),
        ),
    ]
