# Generated by Django 2.2.2 on 2020-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0119_auto_20190620_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='alpha',
            field=models.FloatField(default=0.01, help_text='Concentration parameter of Dirichlet distribution of topics in documents (try higher values in LDA, including > 1). Low (high) values indicate that documents should be composed of few (many) topics. Also called theta. In NMF, this is the regularization term alpha', null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='beta',
            field=models.FloatField(blank=True, default=None, help_text='Concentration parameter of Dirichlet distribution of words in topics. Low (high) values indicate that topics should be composed of few (many) words. Also called eta. This parameter is not used in NMF', null=True),
        ),
    ]
