# Generated by Django 2.2 on 2020-01-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0054_auto_20191210_1747'),
        ('scoping', '0315_auto_20200114_1420'),
        ('tmv_app', '0120_auto_20200113_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTopicCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('scaled_score', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.Doc')),
                ('par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Paragraph')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic')),
                ('ut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Utterance')),
            ],
        ),
    ]
