# Generated by Django 2.2.9 on 2020-02-11 17:31

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0315_auto_20200114_1420'),
        ('parliament', '0055_auto_20200206_0942'),
        ('tmv_app', '0121_doctopiccopy'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='DocTopicPartitioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('scaled_score', models.FloatField()),
                ('run_id', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod('range'),
                'key': ['run_id'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='DocTopicPartitioned',
            name='default',
        ),
        migrations.AddField(
            model_name='doctopicpartitioned',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.Doc'),
        ),
        migrations.AddField(
            model_name='doctopicpartitioned',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tmv_app.Topic'),
        ),
        migrations.AddField(
            model_name='doctopicpartitioned',
            name='par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Paragraph'),
        ),
        migrations.AddField(
            model_name='doctopicpartitioned',
            name='ut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Utterance'),
        ),
    ]
