# Generated by Django 2.2.9 on 2020-02-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0055_auto_20200206_0942'),
        ('scoping', '0315_auto_20200114_1420'),
        ('tmv_app', '0123_auto_20200214_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocTopicPartitioned',
            new_name='DocTopic',
        ),
    ]
