# Generated by Django 2.2.9 on 2020-02-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0124_auto_20200214_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocTopicArchive',
        ),
    ]
