# Generated by Django 2.2.9 on 2020-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0125_delete_doctopicarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='lda_library',
            field=models.CharField(choices=[('sk', 'Sklearn'), ('ld', 'lda'), ('wl', 'warplda')], default='sk', help_text='you can use sklearn or https://github.com/lda-project/lda for LDA', max_length=2, null=True),
        ),
    ]
