# Generated by Django 4.2 on 2023-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0126_auto_20200417_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstats',
            name='topic_scores_current',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='topic_titles_current',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='runstats',
            name='topic_year_scores_current',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
