# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('UT', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('PY', models.IntegerField(null=True)),
                ('modkey', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DocInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scoping.Doc')),
                ('ti', models.TextField(null=True)),
                ('ab', models.TextField(null=True)),
                ('py', models.IntegerField(null=True)),
                ('ar', models.IntegerField(null=True)),
                ('bn', models.CharField(max_length=100)),
                ('bp', models.IntegerField(null=True)),
                ('c1', models.TextField(null=True)),
                ('cl', models.TextField(null=True)),
                ('ct', models.TextField(null=True)),
                ('de', models.TextField(null=True)),
                ('di', models.CharField(max_length=150, null=True)),
                ('dt', models.CharField(max_length=50, null=True)),
                ('em', models.EmailField(max_length=254, null=True)),
                ('ep', models.IntegerField(null=True)),
                ('fn', models.CharField(max_length=100, null=True)),
                ('fu', models.TextField(null=True)),
                ('fx', models.TextField(null=True)),
                ('ga', models.CharField(max_length=100, null=True)),
                ('ho', models.TextField(null=True)),
                ('j9', models.CharField(max_length=30, null=True)),
                ('ji', models.CharField(max_length=50, null=True)),
                ('la', models.CharField(max_length=50, null=True)),
                ('nr', models.IntegerField(null=True)),
                ('pa', models.TextField(null=True)),
                ('pd', models.CharField(max_length=5, null=True)),
                ('pg', models.IntegerField(null=True)),
                ('pi', models.TextField(null=True)),
                ('pt', models.CharField(max_length=50, null=True)),
                ('pu', models.TextField(null=True)),
                ('rp', models.TextField(null=True)),
                ('sc', models.TextField(null=True)),
                ('se', models.TextField(null=True)),
                ('si', models.TextField(null=True)),
                ('sn', models.CharField(max_length=50, null=True)),
                ('so', models.CharField(max_length=50, null=True)),
                ('sp', models.TextField(null=True)),
                ('su', models.TextField(null=True)),
                ('tc', models.IntegerField(null=True)),
                ('vl', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='docinstitutions',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc'),
        ),
        migrations.AddField(
            model_name='docauthors',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc'),
        ),
    ]
