# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAuthInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_index=True, max_length=60)),
                ('institution', models.CharField(db_index=True, max_length=60)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocCites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('date', models.DateTimeField()),
                ('r_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='WoSArticle',
        ),
        migrations.RemoveField(
            model_name='docauthors',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='docinstitutions',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='modkey',
        ),
        migrations.AlterField(
            model_name='doc',
            name='PY',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='DocAuthors',
        ),
        migrations.DeleteModel(
            name='DocInstitutions',
        ),
        migrations.AddField(
            model_name='doccites',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='scoping.Doc'),
        ),
        migrations.AddField(
            model_name='doccites',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='scoping.Doc'),
        ),
        migrations.AddField(
            model_name='docauthinst',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc'),
        ),
        migrations.AddField(
            model_name='doc',
            name='query',
            field=models.ManyToManyField(to='scoping.Query'),
        ),
    ]
