# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0002_auto_20161207_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.TextField(null=True, unique=True),
        ),
    ]
