# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0003_auto_20161208_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docauthinst',
            name='author',
        ),
        migrations.AddField(
            model_name='docauthinst',
            name='AF',
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='docauthinst',
            name='AU',
            field=models.CharField(db_index=True, max_length=60, null=True),
        ),
    ]
