# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0005_auto_20161208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docauthinst',
            name='institution',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
