# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0008_auto_20161212_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ji',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
