# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0009_auto_20161212_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='bn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='la',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='sn',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
