# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0012_auto_20161212_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='fn',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
