# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0013_auto_20161212_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ga',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
