# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0016_auto_20161212_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ar',
            field=models.CharField(max_length=100, null=True, verbose_name='article number'),
        ),
    ]
