# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0017_auto_20161212_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ab',
            field=models.TextField(null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='bn',
            field=models.CharField(max_length=100, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='bp',
            field=models.CharField(max_length=5, null=True, verbose_name='Beginning Page'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='c1',
            field=models.TextField(null=True, verbose_name='Author Address'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='cl',
            field=models.TextField(null=True, verbose_name='Conference Location'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ct',
            field=models.TextField(null=True, verbose_name='Conference Title'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='de',
            field=models.TextField(null=True, verbose_name='Author Keywords'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='py',
            field=models.IntegerField(null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ti',
            field=models.TextField(null=True, verbose_name='Title'),
        ),
    ]
