# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0018_auto_20161212_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='Tag Tigle')),
                ('text', models.TextField(null=True, verbose_name='Tag Text')),
            ],
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='AF',
            field=models.CharField(db_index=True, max_length=60, null=True, verbose_name='Author Full Name'),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='AU',
            field=models.CharField(db_index=True, max_length=60, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc', verbose_name='Author - Document'),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='institution',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='position',
            field=models.IntegerField(verbose_name='Author Position'),
        ),
        migrations.AlterField(
            model_name='query',
            name='date',
            field=models.DateTimeField(verbose_name='Query Date'),
        ),
        migrations.AlterField(
            model_name='query',
            name='r_count',
            field=models.IntegerField(null=True, verbose_name='Query Results Count'),
        ),
        migrations.AlterField(
            model_name='query',
            name='text',
            field=models.TextField(null=True, verbose_name='Query Text'),
        ),
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.TextField(null=True, unique=True, verbose_name='Query Title'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Article Number'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='di',
            field=models.CharField(max_length=150, null=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='dt',
            field=models.CharField(max_length=50, null=True, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='em',
            field=models.TextField(null=True, verbose_name='E-mail Address'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ep',
            field=models.CharField(max_length=5, null=True, verbose_name='Ending Page'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='fn',
            field=models.CharField(max_length=150, null=True, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='fu',
            field=models.TextField(null=True, verbose_name='Funding Agency and Grant Number'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='fx',
            field=models.TextField(null=True, verbose_name='Funding Text'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ga',
            field=models.CharField(max_length=100, null=True, verbose_name='Document Delivery Number'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ho',
            field=models.TextField(null=True, verbose_name='Conference Host'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='j9',
            field=models.CharField(max_length=30, null=True, verbose_name='29-Character Source Abbreviation'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ji',
            field=models.CharField(max_length=100, null=True, verbose_name='ISO Source Abbreviation'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='la',
            field=models.CharField(max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='nr',
            field=models.IntegerField(null=True, verbose_name='Cited Reference Count'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pa',
            field=models.TextField(null=True, verbose_name='Publisher Address'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pd',
            field=models.CharField(max_length=10, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pg',
            field=models.IntegerField(null=True, verbose_name='Page Count'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pi',
            field=models.TextField(null=True, verbose_name='Publisher City'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pt',
            field=models.CharField(max_length=50, null=True, verbose_name='Publication Type'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pu',
            field=models.TextField(null=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='rp',
            field=models.TextField(null=True, verbose_name='Reprint Address'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='sc',
            field=models.TextField(null=True, verbose_name='Subject Category'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='se',
            field=models.TextField(null=True, verbose_name='Book Series Title'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='si',
            field=models.TextField(null=True, verbose_name='Special Issue'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='sn',
            field=models.CharField(max_length=80, null=True, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='so',
            field=models.CharField(max_length=150, null=True, verbose_name='Publication Name'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='sp',
            field=models.TextField(null=True, verbose_name='Conference Sponsors'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='su',
            field=models.TextField(null=True, verbose_name='Supplement'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='tc',
            field=models.IntegerField(null=True, verbose_name='Times Cited'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='vl',
            field=models.CharField(max_length=10, null=True, verbose_name='Volume'),
        ),
        migrations.AddField(
            model_name='doc',
            name='tag',
            field=models.ManyToManyField(to='scoping.Tag'),
        ),
    ]
