# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0019_auto_20161215_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Query', verbose_name='TagQuery'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.TextField(null=True, verbose_name='Tag Title'),
        ),
    ]
