# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0020_auto_20161215_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
