# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0021_query_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Query')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='users',
            field=models.ManyToManyField(through='scoping.DocOwnership', to=settings.AUTH_USER_MODEL),
        ),
    ]
