# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0022_auto_20161215_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='relevant',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
