# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0025_auto_20161220_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ep',
            field=models.CharField(max_length=10, null=True, verbose_name='Ending Page'),
        ),
    ]
