# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0026_auto_20161220_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docownership',
            name='relevant',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Relevance'),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
    ]
