# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0027_auto_20161220_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='criteria',
            field=models.TextField(null=True),
        ),
    ]
