# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0028_query_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Tag'),
        ),
    ]
