# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0029_docownership_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='kwp',
            field=models.TextField(null=True, verbose_name='Keywords Plus'),
        ),
    ]
