# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0030_wosarticle_kwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='type',
            field=models.TextField(null=True, unique=True, verbose_name='Query Type'),
        ),
    ]
