# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0031_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='type',
            field=models.TextField(null=True, verbose_name='Query Type'),
        ),
    ]
