# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0032_auto_20170206_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnowballingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True, verbose_name='SB Name')),
                ('initial_pearls', models.TextField(null=True, verbose_name='SB Initial Pearls')),
                ('date', models.DateTimeField(verbose_name='SB Date')),
                ('completed', models.BooleanField(verbose_name='Is SB Completed')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='snowball',
            field=models.IntegerField(null=True, verbose_name='Snowball ID'),
        ),
    ]
