# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0033_auto_20170206_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snowballingsession',
            name='completed',
        ),
    ]
