# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0036_docreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='docreferences',
            name='refall',
            field=models.TextField(null=True, verbose_name='All reference information'),
        ),
    ]
