# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0037_docreferences_refall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doccites',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='doccites',
            name='reference',
        ),
        migrations.AddField(
            model_name='doc',
            name='references',
            field=models.ManyToManyField(to='scoping.Doc'),
        ),
        migrations.DeleteModel(
            name='DocCites',
        ),
    ]
