# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0038_auto_20170207_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='database',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
