# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0038_auto_20170207_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='step',
            field=models.IntegerField(null=True, verbose_name='Snowball steps'),
        ),
        migrations.AddField(
            model_name='query',
            name='substep',
            field=models.IntegerField(null=True, verbose_name='Snowball query substeps'),
        ),
    ]
