# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0039_auto_20170208_1035'),
        ('scoping', '0039_query_database'),
    ]

    operations = [
    ]
