# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0040_merge_20170208_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='database',
            field=models.CharField(max_length=6, null=True, verbose_name='Query database'),
        ),
    ]
