# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0041_auto_20170208_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='ad',
            field=models.TextField(null=True, verbose_name='Institution (unlinked to author'),
        ),
    ]
