# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0042_wosarticle_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='iss',
            field=models.CharField(max_length=100, null=True, verbose_name='Issue'),
        ),
    ]
