# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0044_auto_20170209_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='UT',
            field=models.CharField(db_index=True, max_length=240, primary_key=True, serialize=False),
        ),
    ]
