# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0045_auto_20170209_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Technology Name')),
                ('description', models.TextField(null=True, verbose_name='Technology Description')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='technology',
            field=models.ManyToManyField(null=True, to='scoping.Technology'),
        ),
        migrations.AddField(
            model_name='query',
            name='technology',
            field=models.ManyToManyField(null=True, to='scoping.Technology'),
        ),
    ]
