# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0047_auto_20170209_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='technology',
        ),
        migrations.AddField(
            model_name='query',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Technology'),
        ),
    ]
