# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0052_auto_20170215_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowballingsession',
            name='status',
            field=models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed')], db_index=True, default=0, verbose_name='SB Status'),
        ),
    ]
