# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0053_snowballingsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='di',
            field=models.CharField(max_length=250, null=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='fn',
            field=models.CharField(max_length=250, null=True, verbose_name='File Name'),
        ),
    ]
