# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0054_auto_20170313_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docauthinst',
            name='institution',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Institution Name'),
        ),
    ]
