# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0055_auto_20170313_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='so',
            field=models.CharField(max_length=250, null=True, verbose_name='Publication Name'),
        ),
    ]
