# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0056_auto_20170313_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='bp',
            field=models.CharField(max_length=50, null=True, verbose_name='Beginning Page'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='ep',
            field=models.CharField(max_length=50, null=True, verbose_name='Ending Page'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pd',
            field=models.CharField(max_length=50, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='vl',
            field=models.CharField(max_length=50, null=True, verbose_name='Volume'),
        ),
    ]
