# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0058_docownership_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docownership',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Rating Date'),
        ),
    ]
