# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0059_auto_20170314_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleShingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shingle', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
    ]
