# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0060_titleshingle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleshingle',
            name='shingle',
        ),
        migrations.AddField(
            model_name='titleshingle',
            name='s1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='titleshingle',
            name='s2',
            field=models.TextField(null=True),
        ),
    ]
