# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0061_auto_20170315_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleshingle',
            name='doc',
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scoping.Doc', verbose_name='Document ID'),
        ),
        migrations.DeleteModel(
            name='TitleShingle',
        ),
    ]
