# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0062_auto_20170317_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='UT',
            field=models.CharField(db_index=True, max_length=240, primary_key=True, serialize=False, verbose_name='Document ID'),
        ),
    ]
