# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0063_auto_20170317_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='di',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='DOI'),
        ),
    ]
