# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0066_query_dlstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowballingsession',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Technology'),
        ),
    ]
