# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0068_snowballingsession_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField()),
                ('text', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('au', models.TextField(null=True)),
                ('PY', models.IntegerField(null=True)),
                ('journal', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('doi', models.TextField(null=True)),
                ('hasdoi', models.BooleanField(default=False)),
                ('docmatch_q', models.BooleanField(default=False)),
                ('timatch_q', models.BooleanField(default=False)),
                ('indb', models.IntegerField()),
                ('sametech', models.IntegerField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
    ]
