# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0068_snowballingsession_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBSDocCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='SBS Document Category Name')),
                ('description', models.TextField(null=True, verbose_name='SBS Document Category Description')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='category',
            field=models.ManyToManyField(to='scoping.SBSDocCategory'),
        ),
    ]
