# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0069_auto_20170406_0908'),
        ('scoping', '0069_auto_20170406_1544'),
    ]

    operations = [
    ]
