# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0071_auto_20170406_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='docrel',
            name='referent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='scoping.Doc'),
        ),
        migrations.AlterField(
            model_name='docrel',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='scoping.Doc'),
        ),
    ]
