# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0073_docrel_seedquery'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docrel',
            unique_together=set([('seed', 'seedquery', 'text')]),
        ),
    ]
