# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0074_auto_20170407_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocKW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
        migrations.CreateModel(
            name='KW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dockw',
            name='kw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.KW'),
        ),
        migrations.AlterUniqueTogether(
            name='dockw',
            unique_together=set([('doc', 'kw')]),
        ),
    ]
