# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0075_auto_20170407_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dockw',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dockw',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='dockw',
            name='kw',
        ),
        migrations.AddField(
            model_name='kw',
            name='doc',
            field=models.ManyToManyField(to='scoping.Doc'),
        ),
        migrations.DeleteModel(
            name='DocKW',
        ),
    ]
