# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0076_auto_20170407_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='kw',
            name='ndocs',
            field=models.IntegerField(default=0),
        ),
    ]
