# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0077_kw_ndocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrel',
            name='indb',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='docrel',
            name='sametech',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
