# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0078_auto_20170407_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='refdblen',
        ),
        migrations.RemoveField(
            model_name='query',
            name='refscraplen',
        ),
        migrations.RemoveField(
            model_name='query',
            name='reftotlen',
        ),
        migrations.AlterField(
            model_name='query',
            name='snowball',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.SnowballingSession', verbose_name='Snowball ID'),
        ),
    ]
