# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0079_auto_20170410_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowballingsession',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
