# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0080_snowballingsession_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowballingsession',
            name='working_pb2',
            field=models.BooleanField(default=False),
        ),
    ]
