# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-19 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0081_snowballingsession_working_pb2'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
