# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0082_auto_20170419_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, verbose_name='Innovation Name')),
                ('description', models.TextField(null=True, verbose_name='Innovation Description')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='innovation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Innovation'),
        ),
    ]
