# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0084_auto_20170420_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCCRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField()),
                ('year', models.IntegerField()),
                ('text', models.TextField()),
                ('ar', models.IntegerField()),
                ('wg', models.IntegerField()),
            ],
        ),
    ]
