# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0086_auto_20170424_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ar',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ar',
            name='start',
            field=models.IntegerField(null=True),
        ),
    ]
