# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 09:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0087_auto_20170424_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='wc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
