# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0089_wc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wc',
            name='oecd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wc',
            name='oecd_fos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wc',
            name='oecd_fos_text',
            field=models.TextField(null=True),
        ),
    ]
