# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0090_auto_20170426_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='scopus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc',
            name='wos',
            field=models.BooleanField(default=False),
        ),
    ]
