# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0093_ipccref_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='ndocs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='nqs',
            field=models.IntegerField(null=True),
        ),
    ]
