# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0094_auto_20170510_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTokens',
            fields=[
                ('email', models.TextField()),
                ('AU', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
