# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0095_emailtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='technology',
            field=models.ManyToManyField(db_index=True, to='scoping.Technology'),
        ),
    ]
