# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-11 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0096_auto_20170511_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='em',
            field=models.TextField(db_index=True, null=True, verbose_name='E-mail Address'),
        ),
    ]
