# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0098_auto_20170511_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrel',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
