# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0100_doc_innovation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docownership',
            name='relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Maybe'), (4, 'Other Technology'), (5, 'Tech Relevant & Innovation Relevant'), (6, 'Tech Relevant & Innovation Irrelevant'), (7, 'Tech Irrelevant & Innovation Relevant'), (8, 'Tech Irrelevant & Innovation Irrelevant')], db_index=True, default=0, verbose_name='Relevance'),
        ),
    ]
