# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        ('scoping', '0102_doc_ymentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='cities',
            field=models.ManyToManyField(to=settings.CITIES_CITY_MODEL),
        ),
    ]
