# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 11:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0104_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='cr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
