# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 12:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0105_wosarticle_cr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au', models.TextField(null=True)),
                ('py', models.IntegerField(null=True)),
                ('so', models.TextField(null=True)),
                ('vl', models.IntegerField(null=True)),
                ('bp', models.IntegerField(null=True)),
                ('doi', models.TextField(db_index=True, null=True, unique=True)),
                ('ftext', models.TextField(db_index=True, unique=True)),
                ('alt_text', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
            ],
        ),
    ]
