# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0107_cdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='ftext',
            field=models.TextField(db_index=True),
        ),
    ]
