# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import scoping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0108_auto_20170706_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibCouple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocites', models.IntegerField(default=0, verbose_name=scoping.models.Doc)),
                ('doc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node1', to='scoping.Doc')),
                ('doc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node2', to='scoping.Doc')),
            ],
        ),
    ]
