# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0109_bibcouple'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='k',
            field=models.IntegerField(null=True),
        ),
    ]
