# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0111_auto_20170710_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.IntegerField(db_index=True, null=True)),
                ('degree', models.FloatField(db_index=True, null=True)),
                ('eigen_cent', models.FloatField(db_index=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='degree',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='eigen_cent',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='networkproperties',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc'),
        ),
        migrations.AddField(
            model_name='networkproperties',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Query'),
        ),
    ]
