# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0112_auto_20170710_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='citation_objects',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
