# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0113_doc_citation_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='distance',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
