# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0114_doc_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtokens',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
