# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0115_emailtokens_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtokens',
            name='docset',
            field=models.TextField(null=True),
        ),
    ]
