# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0116_emailtokens_docset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem1', models.TextField(db_index=True)),
                ('word1', models.TextField()),
                ('word2', models.TextField()),
                ('stem2', models.TextField()),
                ('pos', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocBigram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(null=True)),
                ('bigram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Bigram')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
    ]
