# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-20 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0120_auto_20170720_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkproperties',
            name='doc',
        ),
        migrations.DeleteModel(
            name='NetworkProperties',
        ),
    ]
