# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0122_networkproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='duplicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
