# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0123_auto_20170721_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(db_index=True, unique=True)),
            ],
        ),
    ]
