# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0124_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
    ]
