# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 09:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0127_doc_projects'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='wosarticle',
        #     name='c1',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Author Address'),
        # ),
    ]
