# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0130_auto_20170815_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='docs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='queries',
            field=models.IntegerField(null=True),
        ),
    ]
