# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0133_auto_20171011_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='docs',
            field=models.IntegerField(default=0),
        ),
    ]
