# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0134_auto_20171011_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docauthinst',
            unique_together=set([('doc', 'AU', 'AF', 'institution', 'position')]),
        ),
    ]
