# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0136_doc_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='authors',
            field=models.TextField(null=True, verbose_name='All Authors'),
        ),
    ]
