# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0138_doc_first_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tms',
            field=models.IntegerField(default=0),
        ),
    ]
