# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0140_auto_20171018_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='UT',
            fields=[
                ('UT', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, verbose_name='Document ID')),
            ],
        ),
    ]
