# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0141_ut'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='UT_copy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
