# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0142_doc_ut_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scoping.UT')),
            ],
        ),
    ]
