# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0143_doc_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocProject_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant', models.BooleanField(default=False)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_copy')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
            ],
        ),
    ]
