# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0144_docproject_copy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc_copy',
            new_name='Doc_2',
        ),
    ]
