# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0145_auto_20171020_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocBigram_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(null=True)),
                ('bigram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Bigram')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_2')),
            ],
        ),
    ]
