# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0147_cdo_copy_citation_copy_networkproperties_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdo_copy',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='cdo_copy',
            name='doc',
        ),
        migrations.DeleteModel(
            name='CDO_copy',
        ),
    ]
