# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0149_cdo_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation_copy',
            name='referent',
        ),
        migrations.DeleteModel(
            name='Citation_copy',
        ),
    ]
