# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0153_networkproperties_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdo_copy',
            name='citation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Citation_copy'),
        ),
    ]
