# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0155_bibcouple_copy_ipccref_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='KW_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ndocs', models.IntegerField(default=0)),
                ('doc', models.ManyToManyField(to='scoping.Doc_2')),
            ],
        ),
        migrations.CreateModel(
            name='WC_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('oecd', models.TextField(null=True)),
                ('oecd_fos', models.TextField(null=True)),
                ('oecd_fos_text', models.TextField(null=True)),
                ('doc', models.ManyToManyField(to='scoping.Doc_2')),
            ],
        ),
    ]
