# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0156_kw_copy_wc_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRel_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField()),
                ('text', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('au', models.TextField(null=True)),
                ('PY', models.IntegerField(null=True)),
                ('journal', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('doi', models.TextField(null=True)),
                ('hasdoi', models.BooleanField(default=False)),
                ('docmatch_q', models.BooleanField(default=False)),
                ('timatch_q', models.BooleanField(default=False)),
                ('indb', models.IntegerField(default=0, null=True)),
                ('sametech', models.IntegerField(default=0, null=True)),
                ('referent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='scoping.Doc_2')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='scoping.Doc_2')),
                ('seedquery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Query')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='docrel_copy',
            unique_together=set([('seed', 'seedquery', 'text')]),
        ),
    ]
