# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0157_auto_20171020_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocOwnership_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant', models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Maybe'), (4, 'Other Technology'), (5, 'Tech Relevant & Innovation Relevant'), (6, 'Tech Relevant & Innovation Irrelevant'), (7, 'Tech Irrelevant & Innovation Relevant'), (8, 'Tech Irrelevant & Innovation Irrelevant')], db_index=True, default=0, verbose_name='Relevance')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Rating Date')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_2')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Query')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Note_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.TextField(null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Notemaker')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
