# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 13:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0158_docownership_copy_note_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAuthInst_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AU', models.CharField(db_index=True, max_length=60, null=True, verbose_name='Author')),
                ('AF', models.CharField(db_index=True, max_length=60, null=True, verbose_name='Author Full Name')),
                ('institution', models.CharField(db_index=True, max_length=250, verbose_name='Institution Name')),
                ('position', models.IntegerField(verbose_name='Author Position')),
            ],
        ),
        migrations.CreateModel(
            name='DocReferences_copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refdoi', models.CharField(max_length=150, null=True, verbose_name='DOI')),
                ('refall', models.TextField(null=True, verbose_name='All reference information')),
            ],
        ),
        migrations.CreateModel(
            name='WoSArticle_copy',
            fields=[
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scoping.Doc_2', verbose_name='Document ID')),
                ('pt', models.CharField(max_length=50, null=True, verbose_name='Publication Type')),
                ('ti', models.TextField(null=True, verbose_name='Title')),
                ('ab', models.TextField(null=True, verbose_name='Abstract')),
                ('py', models.IntegerField(null=True, verbose_name='Year')),
                ('ar', models.CharField(max_length=100, null=True, verbose_name='Article Number')),
                ('bn', models.CharField(max_length=100, null=True, verbose_name='ISBN')),
                ('bp', models.CharField(max_length=50, null=True, verbose_name='Beginning Page')),
                ('c1', models.TextField(null=True, verbose_name='Author Address')),
                ('cl', models.TextField(null=True, verbose_name='Conference Location')),
                ('cr', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Cited References')),
                ('ct', models.TextField(null=True, verbose_name='Conference Title')),
                ('de', models.TextField(null=True, verbose_name='Author Keywords')),
                ('di', models.CharField(db_index=True, max_length=250, null=True, verbose_name='DOI')),
                ('dt', models.CharField(max_length=50, null=True, verbose_name='Document Type')),
                ('em', models.TextField(db_index=True, null=True, verbose_name='E-mail Address')),
                ('ep', models.CharField(max_length=50, null=True, verbose_name='Ending Page')),
                ('fn', models.CharField(max_length=250, null=True, verbose_name='File Name')),
                ('fu', models.TextField(null=True, verbose_name='Funding Agency and Grant Number')),
                ('fx', models.TextField(null=True, verbose_name='Funding Text')),
                ('ga', models.CharField(max_length=100, null=True, verbose_name='Document Delivery Number')),
                ('ho', models.TextField(null=True, verbose_name='Conference Host')),
                ('iss', models.CharField(max_length=100, null=True, verbose_name='Issue')),
                ('ad', models.TextField(null=True, verbose_name='Institution (unlinked to author')),
                ('kwp', models.TextField(null=True, verbose_name='Keywords Plus')),
                ('j9', models.CharField(max_length=30, null=True, verbose_name='29-Character Source Abbreviation')),
                ('ji', models.CharField(max_length=100, null=True, verbose_name='ISO Source Abbreviation')),
                ('la', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('nr', models.IntegerField(null=True, verbose_name='Cited Reference Count')),
                ('pa', models.TextField(null=True, verbose_name='Publisher Address')),
                ('pd', models.CharField(max_length=50, null=True, verbose_name='Publication Date')),
                ('pg', models.IntegerField(null=True, verbose_name='Page Count')),
                ('pi', models.TextField(null=True, verbose_name='Publisher City')),
                ('pu', models.TextField(null=True, verbose_name='Publisher')),
                ('rp', models.TextField(null=True, verbose_name='Reprint Address')),
                ('sc', models.TextField(null=True, verbose_name='Subject Category')),
                ('se', models.TextField(null=True, verbose_name='Book Series Title')),
                ('si', models.TextField(null=True, verbose_name='Special Issue')),
                ('sn', models.CharField(max_length=80, null=True, verbose_name='ISSN')),
                ('so', models.CharField(max_length=250, null=True, verbose_name='Publication Name')),
                ('sp', models.TextField(null=True, verbose_name='Conference Sponsors')),
                ('su', models.TextField(null=True, verbose_name='Supplement')),
                ('tc', models.IntegerField(null=True, verbose_name='Times Cited')),
                ('vl', models.CharField(max_length=50, null=True, verbose_name='Volume')),
                ('wc', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='docreferences_copy',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_2'),
        ),
        migrations.AddField(
            model_name='docauthinst_copy',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc_2', verbose_name='Author - Document'),
        ),
        migrations.AlterUniqueTogether(
            name='docauthinst_copy',
            unique_together=set([('doc', 'AU', 'AF', 'institution', 'position')]),
        ),
    ]
