# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 14:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0159_auto_20171020_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_2',
            name='PY',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='authors',
            field=models.TextField(null=True, verbose_name='All Authors'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='category',
            field=models.ManyToManyField(to='scoping.SBSDocCategory'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='citation_objects',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='cities',
            field=models.ManyToManyField(to=settings.CITIES_CITY_MODEL),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='duplicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='first_author',
            field=models.TextField(null=True, verbose_name='First Author'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='innovation',
            field=models.ManyToManyField(db_index=True, to='scoping.Innovation'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='projects',
            field=models.ManyToManyField(through='scoping.DocProject_copy', to='scoping.Project'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='query',
            field=models.ManyToManyField(to='scoping.Query'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='scopus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='tag',
            field=models.ManyToManyField(to='scoping.Tag'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='technology',
            field=models.ManyToManyField(db_index=True, to='scoping.Technology'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='tilength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='users',
            field=models.ManyToManyField(through='scoping.DocOwnership_copy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='wos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doc_2',
            name='ymentions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='doc',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs_2', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
