# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0161_auto_20171025_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc_2',
            new_name='Doc',
        ),
    ]
