# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0162_auto_20171025_0857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BibCouple_copy',
            new_name='BibCouple',
        ),
        migrations.RenameModel(
            old_name='CDO_copy',
            new_name='CDO',
        ),
        migrations.RenameModel(
            old_name='Citation_copy',
            new_name='Citation',
        ),
        migrations.RenameModel(
            old_name='DocAuthInst_copy',
            new_name='DocAuthInst',
        ),
        migrations.RenameModel(
            old_name='DocBigram_copy',
            new_name='DocBigram',
        ),
        migrations.RenameModel(
            old_name='DocOwnership_copy',
            new_name='DocOwnership',
        ),
        migrations.RenameModel(
            old_name='DocProject_copy',
            new_name='DocProject',
        ),
        migrations.RenameModel(
            old_name='DocReferences_copy',
            new_name='DocReferences',
        ),
        migrations.RenameModel(
            old_name='DocRel_copy',
            new_name='DocRel',
        ),
        migrations.RenameModel(
            old_name='IPCCRef_copy',
            new_name='IPCCRef',
        ),
        migrations.RenameModel(
            old_name='KW_copy',
            new_name='KW',
        ),
        migrations.RenameModel(
            old_name='NetworkProperties_copy',
            new_name='NetworkProperties',
        ),
        migrations.RenameModel(
            old_name='Note_copy',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='WC_copy',
            new_name='WC',
        ),
        migrations.RenameModel(
            old_name='WoSArticle_copy',
            new_name='WoSArticle',
        ),
    ]
