# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0165_doc_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalabbrev',
            name='fulltext',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
