# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmv_app', '0055_runstats_empty_topics'),
        ('scoping', '0167_auto_20171115_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='primary_topic',
            field=models.ManyToManyField(to='tmv_app.Topic'),
        ),
    ]
