# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 12:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0168_doc_primary_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtokens',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Technology'),
        ),
        migrations.AddField(
            model_name='emailtokens',
            name='sent_other_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='wc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Web of Science Category'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtokens',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='emailtokens',
            index_together=set([]),
        ),
    ]
