# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0169_auto_20171129_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtokens',
            name='sent_other_tech',
            field=models.BooleanField(default=False),
        ),
    ]
