# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0171_query_qtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='upload_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.EmailTokens'),
        ),
    ]
