# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0172_query_upload_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='dtype',
            field=models.CharField(choices=[('AR', 'Article'), ('RE', 'Review'), ('BC', 'Book Chapter'), ('BK', 'Book'), ('WP', 'Working Paper')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='docfile',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc'),
        ),
    ]
