# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0173_auto_20171130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
