# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0174_auto_20171130_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='docauthinst',
            name='initials',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='docauthinst',
            name='surname',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='dtype',
            field=models.CharField(choices=[('AR', 'Article'), ('RE', 'Review'), ('BC', 'Book Chapter'), ('BK', 'Book'), ('WP', 'Working Paper')], help_text='Tell us what type of document you are adding', max_length=2, null=True, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='so',
            field=models.CharField(help_text='Enter the name of the journal or the title of the book', max_length=250, null=True, verbose_name='Publication Name'),
        ),
    ]
