# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import scoping.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0175_auto_20171201_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dtype',
            field=models.CharField(choices=[('AR', 'Article'), ('RP', 'Report'), ('BC', 'Book Chapter'), ('BK', 'Book'), ('WP', 'Working Paper')], help_text='Tell us what type of document you are adding', max_length=2, null=True, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='docfile',
            name='file',
            field=models.FileField(upload_to='', validators=[scoping.validators.validate_pdf]),
        ),
    ]
