# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0176_auto_20171205_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtokens',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
