# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0177_emailtokens_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtokens',
            name='valid_docs',
            field=models.IntegerField(default=0),
        ),
    ]
