# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0179_note_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='primary_topic',
        ),
    ]
