# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0180_remove_doc_primary_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email_ending', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Institution'),
        ),
    ]
