# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0183_emailtokens_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
