# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0184_doc_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='fulltext',
            field=models.TextField(null=True),
        ),
    ]
