# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0185_doc_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='ndocs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='nqs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Project'),
        ),
    ]
