# Generated by Django 2.0.5 on 2018-05-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0187_ut_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('n', models.IntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('n', models.IntegerField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
            ],
        ),
        migrations.AddField(
            model_name='docpar',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.DocSection'),
        ),
    ]
