# Generated by Django 2.0.5 on 2018-05-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0188_auto_20180518_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpar',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.DocSection'),
        ),
    ]
