# Generated by Django 2.0.5 on 2018-05-24 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0190_docpar_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='docpar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.DocPar'),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc'),
        ),
    ]
