# Generated by Django 2.0.5 on 2018-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0191_auto_20180524_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='document_linked',
            field=models.BooleanField(default=True),
        ),
    ]
