# Generated by Django 2.0.5 on 2018-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0192_docownership_document_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='document_linked',
            field=models.BooleanField(default=True),
        ),
    ]
