# Generated by Django 2.0.5 on 2018-05-25 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0194_auto_20180525_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
