# Generated by Django 2.0.5 on 2018-05-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0195_auto_20180525_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Tag'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.TextField(null=True, verbose_name='Category Name'),
        ),
    ]
