# Generated by Django 2.0.5 on 2018-05-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0196_auto_20180528_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpar',
            name='endColor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='endFont',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='endFontsize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='imputed_role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='maxX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='maxY',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='minX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='minY',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='mostCommonColor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='mostCommonFont',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='mostCommonFontsize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='startColor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='startFont',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='startFontsize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='docpar',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
