# Generated by Django 2.0.5 on 2018-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0197_auto_20180528_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpar',
            name='text_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Maybe'), (4, 'Other Technology'), (5, 'Tech Relevant & Innovation Relevant'), (6, 'Tech Relevant & Innovation Irrelevant'), (7, 'Tech Irrelevant & Innovation Relevant'), (8, 'Tech Irrelevant & Innovation Irrelevant'), (9, 'Badly Parsed')], db_index=True, default=0, verbose_name='Relevance'),
        ),
    ]
