# Generated by Django 2.0.5 on 2018-06-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0199_technology_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('text_length', models.IntegerField(null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
                ('tag', models.ManyToManyField(to='scoping.Tag')),
                ('technology', models.ManyToManyField(db_index=True, to='scoping.Technology')),
            ],
        ),
    ]
