# Generated by Django 2.0.5 on 2018-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0200_docstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docstatement',
            name='tag',
        ),
    ]
