# Generated by Django 2.0.5 on 2018-06-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0202_auto_20180607_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='docstat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.DocStatement'),
        ),
    ]
