# Generated by Django 2.0.5 on 2018-06-19 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0205_remove_docownership_docstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='finish',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Rating Date'),
        ),
        migrations.AddField(
            model_name='docownership',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Rating Date'),
        ),
    ]
