# Generated by Django 2.0.5 on 2018-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0206_auto_20180619_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docownership',
            name='finish',
            field=models.DateTimeField(null=True, verbose_name='Rating Date'),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Rating Date'),
        ),
    ]
