# Generated by Django 2.0.5 on 2018-07-19 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0209_auto_20180704_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framing_unit', models.TextField(null=True)),
                ('timing', models.TextField(null=True)),
                ('payment', models.TextField(null=True)),
                ('granularity', models.TextField(null=True)),
                ('medium', models.TextField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('followup', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterventionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField()),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StudyEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('statistical_technique', models.TextField()),
                ('dependent_variable', models.TextField()),
                ('control_definition', models.TextField(null=True)),
                ('aggregation_level', models.TextField(null=True)),
                ('total_sample_size', models.IntegerField()),
                ('treatment_sample_size', models.IntegerField()),
                ('treated_mean', models.FloatField(null=True)),
                ('control_mean', models.FloatField(null=True)),
                ('diff_mean', models.IntegerField(null=True)),
                ('treated_sd', models.FloatField(null=True)),
                ('control_sd', models.FloatField(null=True)),
                ('pooled_sd', models.FloatField(null=True)),
                ('coefficient', models.FloatField(null=True)),
                ('coefficient_sd', models.FloatField(null=True)),
                ('significance_test', models.TextField()),
                ('test_statistic', models.FloatField()),
                ('test_statistic_df', models.IntegerField()),
                ('p_value', models.FloatField()),
                ('test_tails', models.IntegerField(choices=[(1, 'one-tailed'), (2, 'two-tailed')])),
                ('geographic_scope', models.TextField()),
                ('effect_direction', models.IntegerField()),
                ('controls', models.ManyToManyField(to='scoping.Controls')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interventionsubtype',
            name='interventiontype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.InterventionType'),
        ),
        migrations.AddField(
            model_name='interventionsubtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.StudyEffect'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_subtypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.InterventionSubType'),
        ),
    ]
