# Generated by Django 2.0.5 on 2018-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0210_auto_20180719_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docproject',
            name='relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed')], default=0),
        ),
    ]
