# Generated by Django 2.0.5 on 2018-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0211_auto_20180719_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reldocs',
            field=models.IntegerField(default=0),
        ),
    ]
