# Generated by Django 2.0.5 on 2018-07-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0212_project_reldocs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docproject',
            unique_together={('doc', 'project')},
        ),
    ]
