# Generated by Django 2.0.5 on 2018-08-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0214_docmetacoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
    ]
