# Generated by Django 2.0.5 on 2018-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0215_remove_project_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_file',
            field=models.FileField(null=True, upload_to='queries/'),
        ),
    ]
