# Generated by Django 2.0.5 on 2018-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0216_query_query_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='database',
            field=models.CharField(choices=[('WoS', 'Web of Science'), ('Scopus', 'Scopus'), ('intern', 'Internal')], max_length=6, null=True, verbose_name='Query database'),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='diff_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='effect_direction',
            field=models.IntegerField(choices=[(1, 'positive'), (-1, 'negative')]),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='page',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='total_sample_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='treatment_sample_size',
            field=models.PositiveIntegerField(),
        ),
    ]
