# Generated by Django 2.0.5 on 2018-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0217_auto_20180820_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyeffect',
            name='effect_direction',
            field=models.IntegerField(choices=[(1, 'Positive'), (-1, 'Negative')]),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='test_statistic',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='test_statistic_df',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='total_sample_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='treatment_sample_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
