# Generated by Django 2.0.5 on 2018-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0220_auto_20180822_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyeffect',
            name='geographic_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
