# Generated by Django 2.0.5 on 2018-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0221_auto_20180822_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='all_docs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='cohens_kappa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='irrel_docs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='rel_docs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='relevance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='seen_docs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
