# Generated by Django 2.0.5 on 2018-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0222_auto_20180905_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='intervention_subtypes',
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervention_subtypes',
            field=models.ManyToManyField(to='scoping.InterventionSubType'),
        ),
    ]
