# Generated by Django 2.0.5 on 2018-09-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0223_auto_20180905_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyeffect',
            name='control_definition',
        ),
    ]
