# Generated by Django 2.0.5 on 2018-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0224_remove_studyeffect_control_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='a_docs',
            field=models.IntegerField(default=0, verbose_name='assigned docs'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='all_docs',
            field=models.IntegerField(default=0, verbose_name='all docs'),
        ),
    ]
