# Generated by Django 2.0.5 on 2018-09-13 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0225_auto_20180905_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_docs', models.IntegerField(default=0, verbose_name='assigned docs')),
                ('seen_docs', models.IntegerField(default=0)),
                ('rel_docs', models.IntegerField(default=0)),
                ('irrel_docs', models.IntegerField(default=0)),
                ('relevance', models.FloatField(default=0)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='AF',
            field=models.CharField(db_index=True, max_length=90, null=True, verbose_name='Author Full Name'),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='AU',
            field=models.CharField(db_index=True, max_length=90, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='surname',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
