# Generated by Django 2.0.5 on 2018-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0226_auto_20180913_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='baseline_consumption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='randomisation_method',
            field=models.TextField(null=True),
        ),
    ]
