# Generated by Django 2.0.5 on 2018-09-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0228_auto_20180913_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyeffect',
            name='research_design',
            field=models.TextField(null=True),
        ),
    ]
