# Generated by Django 2.0.5 on 2018-09-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0229_studyeffect_research_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Doc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='baseline_consumption',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='randomisation_method',
        ),
        migrations.RemoveField(
            model_name='studyeffect',
            name='intervention_start_year',
        ),
        migrations.RemoveField(
            model_name='studyeffect',
            name='research_design',
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
