# Generated by Django 2.0.5 on 2018-09-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0230_auto_20180920_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
            ],
        ),
    ]
