# Generated by Django 2.0.5 on 2018-09-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0231_exclusioncriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusioncriteria',
            old_name='text',
            new_name='name',
        ),
    ]
