# Generated by Django 2.0.5 on 2018-10-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0232_auto_20180920_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopChar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('str_value', models.TextField(null=True)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.StudyEffect')),
            ],
        ),
        migrations.CreateModel(
            name='PopCharField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('unit', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='database',
            field=models.CharField(choices=[('WoS', 'Web of Science'), ('Scopus', 'Scopus'), ('intern', 'Internal'), ('pop', 'Publish or Perish')], max_length=6, null=True, verbose_name='Query database'),
        ),
        migrations.AddField(
            model_name='popchar',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.PopCharField'),
        ),
    ]
