# Generated by Django 2.0.5 on 2018-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0233_auto_20181002_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='popcharfield',
            name='numeric',
            field=models.BooleanField(default=False),
        ),
    ]
