# Generated by Django 2.0.5 on 2018-10-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0234_popcharfield_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyeffect',
            name='coefficient_sd_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popcharfield',
            name='unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='database',
            field=models.CharField(choices=[('WoS', 'Web of Science'), ('Scopus', 'Scopus'), ('intern', 'Internal'), ('pop', 'Publish or Perish'), ('ebsco', 'EBSCO')], max_length=6, null=True, verbose_name='Query database'),
        ),
    ]
