# Generated by Django 2.0.5 on 2018-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0235_auto_20181004_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='duration',
            field=models.IntegerField(help_text='weeks', null=True),
        ),
    ]
