# Generated by Django 2.0.5 on 2018-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0239_auto_20181005_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(related_name='child_category', to='scoping.Category'),
        ),
    ]
