# Generated by Django 2.0.5 on 2018-10-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0243_auto_20181005_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docusercat',
            name='project',
        ),
    ]
