# Generated by Django 2.0.5 on 2018-10-05 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0244_remove_docusercat_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusercat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
