# Generated by Django 2.0.5 on 2018-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0245_docusercat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doccat',
            name='association',
        ),
        migrations.AddField(
            model_name='doccat',
            name='query_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doccat',
            name='user_inherited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doccat',
            name='user_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
