# Generated by Django 2.1.2 on 2018-10-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0246_auto_20181005_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='ts',
            field=models.TextField(db_index=True, null=True, verbose_name='Title Abstract Keyword'),
        ),
    ]
