# Generated by Django 2.1.2 on 2018-10-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0247_wosarticle_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ts',
            field=models.TextField(null=True, verbose_name='Title Abstract Keyword'),
        ),
    ]
