# Generated by Django 2.1.2 on 2018-11-02 13:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0248_auto_20181026_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='alternative_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
