# Generated by Django 2.1.2 on 2018-11-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0249_doc_alternative_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicated_by', to='scoping.Doc')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate', to='scoping.Doc')),
            ],
        ),
    ]
