# Generated by Django 2.1.2 on 2018-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0251_auto_20181107_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
