# Generated by Django 2.1.2 on 2018-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0252_duplicate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='title_only',
            field=models.BooleanField(default=False),
        ),
    ]
