# Generated by Django 2.1.2 on 2018-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0253_docownership_title_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='database',
            field=models.CharField(choices=[('WoS', 'Web of Science'), ('Scopus', 'Scopus'), ('intern', 'Internal'), ('pop', 'Publish or Perish'), ('ebsco', 'EBSCO'), ('jstor', 'JSTOR')], max_length=6, null=True, verbose_name='Query database'),
        ),
    ]
