# Generated by Django 2.1.2 on 2018-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0254_auto_20181122_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='upload_log',
            field=models.TextField(null=True),
        ),
    ]
