# Generated by Django 2.1.2 on 2018-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0255_query_upload_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='docproject',
            name='ab_relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed')], default=0),
        ),
        migrations.AddField(
            model_name='docproject',
            name='ti_relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed')], default=0),
        ),
    ]
