# Generated by Django 2.1.2 on 2019-01-03 11:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0256_auto_20181206_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='wosarticle',
            name='ems',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None, verbose_name='Email List'),
        ),
    ]
