# Generated by Django 2.1.2 on 2019-02-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0258_auto_20190205_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='utterance_linked',
            field=models.BooleanField(default=False),
        ),
    ]
