# Generated by Django 2.1.2 on 2019-02-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0259_tag_utterance_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docownership',
            name='utterance_linked',
            field=models.BooleanField(default=False),
        ),
    ]
