# Generated by Django 2.1.2 on 2019-02-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0044_merge_20181026_1551'),
        ('scoping', '0260_auto_20190206_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='utterance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Utterance'),
        ),
    ]
