# Generated by Django 2.1.2 on 2019-02-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0262_auto_20190214_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='credentials',
            field=models.NullBooleanField(),
        ),
    ]
