# Generated by Django 2.1.2 on 2019-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0263_query_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='collections',
            field=models.TextField(null=True),
        ),
    ]
