# Generated by Django 2.1.2 on 2019-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0264_query_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='wos_db',
            field=models.TextField(null=True),
        ),
    ]
