# Generated by Django 2.1.2 on 2019-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0265_query_wos_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ep',
            field=models.CharField(max_length=100, null=True, verbose_name='Ending Page'),
        ),
    ]
