# Generated by Django 2.1.2 on 2019-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0266_auto_20190226_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='ep',
            field=models.CharField(max_length=200, null=True, verbose_name='Ending Page'),
        ),
    ]
