# Generated by Django 2.1.2 on 2019-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0268_auto_20190305_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipccref',
            name='checked_count',
            field=models.IntegerField(default=0),
        ),
    ]
