# Generated by Django 2.1.7 on 2019-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0269_ipccref_checked_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_but',
            field=models.BooleanField(default=False),
        ),
    ]
