# Generated by Django 2.1.7 on 2019-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0270_project_no_but'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='full_text',
            field=models.BooleanField(default=False),
        ),
    ]
