# Generated by Django 2.1.7 on 2019-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0271_docownership_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='docproject',
            name='full_relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed')], default=0),
        ),
    ]
