# Generated by Django 2.2 on 2019-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0274_auto_20190426_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyeffect',
            name='editing_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
    ]
