# Generated by Django 2.2 on 2019-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0275_auto_20190426_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyeffect',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
