# Generated by Django 2.2 on 2019-05-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0277_remove_studyeffect_editing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyeffect',
            name='calculations_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='docmetacoding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.DocMetaCoding'),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='editing_time_elapsed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyeffect',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
