# Generated by Django 2.2 on 2019-05-07 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0279_auto_20190507_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='framing_units',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
