# Generated by Django 2.2 on 2019-05-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0280_intervention_framing_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='framing_unit',
        ),
        migrations.AddField(
            model_name='intervention',
            name='base_data_collection',
            field=models.IntegerField(default=-999, help_text='weeks', null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='treatment_period',
            field=models.IntegerField(default=-999, help_text='weeks', null=True),
        ),
    ]
