# Generated by Django 2.2 on 2019-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('scoping', '0281_auto_20190507_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='regions',
            field=models.ManyToManyField(to='cities.Region'),
        ),
    ]
