# Generated by Django 2.2 on 2019-05-29 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('scoping', '0282_doc_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='countries',
            field=models.ManyToManyField(to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
