# Generated by Django 2.2 on 2019-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0283_doc_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docproject',
            name='ab_relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='full_relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='ti_relevant',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
    ]
