# Generated by Django 2.2 on 2019-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0285_auto_20190604_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='duration',
            field=models.IntegerField(default=-999, help_text='weeks', null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='followup',
            field=models.IntegerField(default=-999, help_text='weeks', null=True),
        ),
    ]
