# Generated by Django 2.2 on 2019-06-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0286_auto_20190604_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='dmc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.DocMetaCoding'),
        ),
        migrations.AddField(
            model_name='note',
            name='effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.StudyEffect'),
        ),
    ]
