# Generated by Django 2.2 on 2019-06-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0289_intervention_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='medium2',
        ),
    ]
