# Generated by Django 2.2 on 2019-06-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0291_docmetacoding_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='docmetacoding',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
