# Generated by Django 2.2 on 2019-06-20 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0292_docmetacoding_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='date',
        ),
        migrations.AddField(
            model_name='doc',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
