# Generated by Django 2.2 on 2019-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0293_auto_20190620_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleVecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField()),
                ('n_docs', models.IntegerField()),
                ('n_vec', models.IntegerField()),
                ('file_path', models.TextField()),
                ('epochs', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('whole_corpus', models.BooleanField()),
            ],
        ),
    ]
