# Generated by Django 2.2 on 2019-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0294_titlevecmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='tslug',
            field=models.TextField(null=True),
        ),
    ]
