# Generated by Django 2.2 on 2019-06-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0295_doc_tslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='tslug',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
