# Generated by Django 2.2 on 2019-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0296_auto_20190620_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dtype',
            field=models.CharField(choices=[('AR', 'Article'), ('RS', 'Regulation/Standard'), ('RP', 'Report'), ('BC', 'Book Chapter'), ('BK', 'Book'), ('WP', 'Working Paper')], help_text='Tell us what type of document you are adding', max_length=2, null=True, verbose_name='Document Type'),
        ),
    ]
