# Generated by Django 2.2 on 2019-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0297_auto_20190625_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
