# Generated by Django 2.2 on 2019-09-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0298_profile_unlimited'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOfBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomisation_control', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Was there a control group in the study?', null=True)),
                ('randomisation_allocation', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Was the allocation between treatment and control group random?', null=True)),
                ('randomisation_differences', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Did the differences between the baseline characteristics of the control and treatment group suggest a problem with the randomisation process?', null=True)),
                ('out_of_sample_bias', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Were the control and treatment group representative of the average population of the corresponding area?', null=True)),
                ('missing_data', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Were data for this outcome available for all, or nearly all, participants randomised? OR was the drop out of the experiment reasonably low?', null=True)),
                ('collection_biases', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Was the process of being observed causing motivation bias (Hawthorne and John Henry effects, courtesy bias, and recall bias)?', null=True)),
                ('reporting_biases', models.IntegerField(choices=[(0, 'Probably Yes'), (2, 'Probably No'), (1, 'Unclear')], help_text='Was the study free from outcome reporting ias and analysis reporting bias?', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='docmetacoding',
            name='risk_of_bias',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.RiskOfBias'),
        ),
    ]
