# Generated by Django 2.2 on 2019-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0300_auto_20190918_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='estimated_docs',
            field=models.IntegerField(null=True),
        ),
    ]
