# Generated by Django 2.2 on 2019-10-07 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0302_project_rating_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docownership',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.Query'),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoping.Tag'),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
    ]
