# Generated by Django 2.2 on 2019-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0304_docownership_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccat',
            name='top_cat',
            field=models.BooleanField(default=False),
        ),
    ]
