# Generated by Django 2.2 on 2019-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0305_doccat_top_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='PY',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
    ]
