# Generated by Django 2.2 on 2019-10-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0306_auto_20191016_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibcouple',
            name='cocites',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='citation',
            name='py',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='docauthinst',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Author Position'),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='docownership',
            name='relevant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Maybe'), (4, 'Other Category'), (5, 'Tech Relevant & Innovation Relevant'), (6, 'Tech Relevant & Innovation Irrelevant'), (7, 'Tech Irrelevant & Innovation Relevant'), (8, 'Tech Irrelevant & Innovation Irrelevant'), (9, 'Badly Parsed')], db_index=True, default=0, verbose_name='Relevance'),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='ab_relevant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='full_relevant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='relevant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='docproject',
            name='ti_relevant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unrated'), (1, 'Yes'), (2, 'No'), (3, 'Mixed'), (4, 'Yes but')], default=0),
        ),
        migrations.AlterField(
            model_name='ipccref',
            name='match_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unchecked'), (1, 'In query'), (2, 'In WoS'), (3, 'Not in WoS')], default=0),
        ),
    ]
