# Generated by Django 2.2 on 2019-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0307_auto_20191016_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wosarticle',
            name='nr',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Cited Reference Count'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='pg',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Page Count'),
        ),
        migrations.AlterField(
            model_name='wosarticle',
            name='py',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Year'),
        ),
    ]
