# Generated by Django 2.2 on 2019-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0308_auto_20191016_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipccref',
            name='tslug',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
