# Generated by Django 2.2 on 2019-12-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0309_ipccref_tslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.TextField(null=True)),
                ('wg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoping.WG')),
            ],
        ),
        migrations.AddField(
            model_name='ipccref',
            name='chapters',
            field=models.ManyToManyField(to='scoping.ARChapter'),
        ),
    ]
