# Generated by Django 2.2.2 on 2020-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0310_auto_20191212_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tweets',
            field=models.IntegerField(default=0),
        ),
    ]
