# Generated by Django 2.2.2 on 2020-01-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0018_searchprogress'),
        ('scoping', '0311_project_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='docownership',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Status'),
        ),
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Project'),
        ),
    ]
