# Generated by Django 2.2.2 on 2020-01-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0019_status_tag'),
        ('scoping', '0313_note_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusercat',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.Status'),
        ),
    ]
