# Generated by Django 2.2.9 on 2020-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0315_auto_20200114_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criteria',
            field=models.TextField(null=True),
        ),
    ]
