# Generated by Django 2.2.9 on 2020-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0318_category_no_further'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique_children',
            field=models.BooleanField(default=False),
        ),
    ]
