# Generated by Django 2.2.9 on 2020-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0319_category_unique_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='equivalents',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_equivalents_+', to='scoping.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_equivalents',
            field=models.BooleanField(default=False),
        ),
    ]
