# Generated by Django 2.2.9 on 2020-03-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0320_auto_20200323_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filtered_equivalents',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='equivalents',
            field=models.ManyToManyField(blank=True, related_name='_category_equivalents_+', to='scoping.Category'),
        ),
    ]
