# Generated by Django 2.2.9 on 2020-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0321_auto_20200323_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_only',
            field=models.BooleanField(default=False),
        ),
    ]
