# Generated by Django 2.2.9 on 2020-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0322_category_title_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
            ],
        ),
    ]
