# Generated by Django 2.2.9 on 2020-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0323_textplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='record_years',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='text_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docusercat',
            name='baseline_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='docusercat',
            name='observation_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='docusercat',
            name='places',
            field=models.ManyToManyField(to='scoping.TextPlace'),
        ),
    ]
