# Generated by Django 2.2.9 on 2020-03-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0324_auto_20200324_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docusercat',
            old_name='baseline_year',
            new_name='baseline_year_1',
        ),
        migrations.RenameField(
            model_name='docusercat',
            old_name='observation_year',
            new_name='observation_year_1',
        ),
    ]
