# Generated by Django 2.2.9 on 2020-04-17 12:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0327_docusercat_duration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doc',
            index=django.contrib.postgres.indexes.GinIndex(fields=('tslug',), name='gin_trgm_idx', opclasses=('gin_trgm_ops',)),
        ),
    ]
