# Generated by Django 2.2.9 on 2020-04-17 12:46

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0328_auto_20200417_1206'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='doc',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='gin_trgm_t_idx', opclasses=('gin_trgm_ops',)),
        ),
    ]
