# Generated by Django 2.2.9 on 2020-04-17 15:56

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0332_auto_20200417_1459'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doc',
            name='gin_trgm_t_idx',
        ),
        migrations.AddIndex(
            model_name='doc',
            index=django.contrib.postgres.indexes.GistIndex(fields=['title'], name='gist_trgm_t_idx', opclasses=('gist_trgm_ops',)),
        ),
    ]
