# Generated by Django 2.2.9 on 2020-04-17 16:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0333_auto_20200417_1556'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='doc',
            name='gist_trgm_t_idx',
        ),
        migrations.AddIndex(
            model_name='doc',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='gin_trgm_t_idx', opclasses=('gin_trgm_ops',)),
        ),
    ]
