# Generated by Django 2.2.2 on 2021-01-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0334_auto_20200417_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country_select',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_category', to='scoping.Category'),
        ),
    ]
