# Generated by Django 2.2.2 on 2021-01-26 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('scoping', '0335_auto_20210126_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusercat',
            name='countries',
            field=models.ManyToManyField(to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
