# Generated by Django 2.2.2 on 2021-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0337_auto_20210126_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selection_tiers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='docusercat',
            name='selection_tier',
            field=models.IntegerField(default=1),
        ),
    ]
