# Generated by Django 2.2.2 on 2021-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0339_profile_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='text_free',
            field=models.BooleanField(default=False),
        ),
    ]
