# Generated by Django 2.2.2 on 2021-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0340_auto_20210311_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusercat',
            name='texts',
            field=models.ManyToManyField(to='scoping.TextFree'),
        ),
    ]
