# Generated by Django 2.2.2 on 2022-06-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0342_auto_20210914_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusercat',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.DocStatement'),
        ),
    ]
