# Generated by Django 4.2 on 2023-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0343_docusercat_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='equivalents',
            field=models.ManyToManyField(blank=True, related_name='equivalent_category', to='scoping.category'),
        ),
        migrations.AlterField(
            model_name='query',
            name='credentials',
            field=models.BooleanField(null=True),
        ),
    ]
