# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 16:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_person_clean_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlsession',
            name='total_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parlsession',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
