# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_auto_20180309_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='parl_period',
        ),
    ]
