# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_remove_document_parl_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='interjection',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='interjection',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
