# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_auto_20180309_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.IntegerField(choices=[(1, 'Applause')])),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Paragraph')),
                ('parties', models.ManyToManyField(to='parliament.Party')),
                ('persons', models.ManyToManyField(to='parliament.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='interjection',
            name='type',
        ),
    ]
