# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_auto_20180312_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Applause'), (2, 'Speech')])),
                ('text', models.TextField(null=True)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Paragraph')),
                ('parties', models.ManyToManyField(to='parliament.Party')),
                ('persons', models.ManyToManyField(to='parliament.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='parties',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='persons',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
