# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0008_auto_20180312_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='colour',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='interjection',
            name='type',
            field=models.IntegerField(choices=[(1, 'Applause'), (2, 'Speech'), (3, 'Objection'), (4, 'Laughter'), (5, 'Outcry')]),
        ),
    ]
