# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0009_auto_20180313_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='search_matches',
            field=models.ManyToManyField(to='parliament.Search'),
        ),
    ]
