# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0010_paragraph_search_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='par_count',
            field=models.IntegerField(default=0, verbose_name='Paragraphs'),
        ),
    ]
