# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0011_search_par_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='parliament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Parl'),
        ),
    ]
