# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0012_party_parliament'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
    ]
