# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0013_person_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='char_len',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
