# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0014_auto_20180316_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='document',
            name='sitting',
            field=models.IntegerField(null=True),
        ),
    ]
