# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0015_auto_20180319_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
