# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_adjust_unique_attributes'),
        ('parliament', '0016_auto_20180320_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituencyVote1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('votes_cast', models.IntegerField(null=True)),
                ('eligible_votes', models.IntegerField(null=True)),
                ('majority', models.FloatField(null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Constituency')),
                ('parlsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParlSession')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Person')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituencyVote2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('votes_cast', models.IntegerField(null=True)),
                ('eligible_votes', models.IntegerField(null=True)),
                ('proportion', models.FloatField(null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='PartyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parlsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParlSession')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Party')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.IntegerField(choices=[(1, 'Direct'), (2, 'List')])),
                ('constituency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Constituency')),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.PartyList')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Person')),
                ('parlsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParlSession')),
            ],
        ),
        migrations.RemoveField(
            model_name='seatresult',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='seatresult',
            name='parlsession',
        ),
        migrations.RemoveField(
            model_name='seatresult',
            name='party',
        ),
        migrations.RemoveField(
            model_name='seatresult',
            name='person',
        ),
        migrations.AddField(
            model_name='post',
            name='cabinet',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SeatResult',
        ),
        migrations.AddField(
            model_name='constituencyvote2',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PartyList'),
        ),
        migrations.AddField(
            model_name='constituencyvote2',
            name='parlsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.ParlSession'),
        ),
        migrations.AddField(
            model_name='constituencyvote2',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
    ]
