# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0017_auto_20180321_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
    ]
