# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0018_person_year_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
