# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0019_person_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='country',
        ),
    ]
