# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0020_remove_constituency_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituencyvote1',
            name='proportion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='constituencyvote1',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
