# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0021_auto_20180321_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='partylist',
            name='party',
        ),
        migrations.AddField(
            model_name='partylist',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.IntegerField(choices=[(1, 'Direct'), (2, 'List')], null=True),
        ),
        migrations.AddField(
            model_name='listmembership',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PartyList'),
        ),
        migrations.AddField(
            model_name='listmembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Person'),
        ),
    ]
