# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0026_auto_20180322_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='partylist',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
        migrations.AddField(
            model_name='seat',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
