# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0027_auto_20180322_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.IntegerField(choices=[(1, 'Direct'), (2, 'List'), (3, 'Volkskammer')], null=True),
        ),
    ]
