# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 10:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0028_auto_20180322_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alt_first_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='alt_surnames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
