# Generated by Django 2.0.5 on 2018-05-18 11:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('parliament', '0029_auto_20180323_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParlSession',
            new_name='ParlPeriod',
        ),
        migrations.RenameField(
            model_name='constituencyvote1',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='constituencyvote2',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='partylist',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='seatsum',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.AddField(
            model_name='person',
            name='in_parlperiod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='search',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
        migrations.AddField(
            model_name='search',
            name='speaker_regions',
            field=models.ManyToManyField(to='cities.Region'),
        ),
        migrations.AlterField(
            model_name='interjection',
            name='type',
            field=models.IntegerField(choices=[(1, 'Applause'), (2, 'Speech'), (3, 'Objection'), (4, 'Amusement'), (5, 'Laughter'), (6, 'Outcry')]),
        ),
    ]
