# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-11 13:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0030_auto_20180430_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParlSession',
            new_name='ParlPeriod',
        ),
        migrations.RenameField(
            model_name='constituencyvote1',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='constituencyvote2',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='partylist',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.RenameField(
            model_name='seatsum',
            old_name='parlsession',
            new_name='parlperiod',
        ),
        migrations.AddField(
            model_name='person',
            name='in_parlperiod',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
