# Generated by Django 2.0.5 on 2018-05-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0030_auto_20180430_1447'),
        ('parliament', '0030_auto_20180518_1123'),
    ]

    operations = [
    ]
