# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('parliament', '0031_auto_20180511_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
        migrations.AddField(
            model_name='search',
            name='speaker_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.Region'),
        ),
    ]
