# Generated by Django 2.0.5 on 2018-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0031_merge_20180711_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='search_object',
            field=models.IntegerField(choices=[(1, 'Paragraph'), (2, 'Utterance')], default=1),
        ),
        migrations.AlterField(
            model_name='search',
            name='par_count',
            field=models.IntegerField(default=0, verbose_name='Number of text objects'),
        ),
    ]
