# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
        ('parliament', '0032_auto_20180516_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='speaker_region',
        ),
        migrations.AddField(
            model_name='search',
            name='speaker_regions',
            field=models.ManyToManyField(to='cities.Region'),
        ),
    ]
