# Generated by Django 2.0.5 on 2018-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0034_auto_20180731_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interjection',
            name='type',
            field=models.IntegerField(choices=[(1, 'Applause'), (2, 'Speech'), (3, 'Objection'), (4, 'Amusement'), (5, 'Laughter'), (6, 'Outcry'), (7, 'Other')]),
        ),
    ]
