# Generated by Django 2.0.5 on 2018-09-04 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0036_auto_20180904_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of entry creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Search creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='document_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Earliest date for search'),
        ),
        migrations.AddField(
            model_name='search',
            name='stop_date',
            field=models.DateTimeField(null=True, verbose_name='Latest date for search'),
        ),
    ]
