# Generated by Django 2.0.5 on 2018-09-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0037_auto_20180904_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='document_source',
            field=models.TextField(null=True, verbose_name='Regex for text_source field of document'),
        ),
        migrations.AlterField(
            model_name='search',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Earliest date for search'),
        ),
        migrations.AlterField(
            model_name='search',
            name='stop_date',
            field=models.DateField(null=True, verbose_name='Latest date for search'),
        ),
    ]
