# Generated by Django 2.0.5 on 2018-09-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0038_auto_20180904_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='par_count',
            field=models.IntegerField(null=True, verbose_name='Number of paragraph objects'),
        ),
        migrations.AlterField(
            model_name='search',
            name='utterance_count',
            field=models.IntegerField(null=True, verbose_name='Number of utterance objects'),
        ),
    ]
