# Generated by Django 2.0.5 on 2018-09-05 11:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CITIES_COUNTRY_MODEL),
        ('parliament', '0039_auto_20180904_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_active', to=settings.CITIES_COUNTRY_MODEL, verbose_name='Country in which the person is active in politics'),
        ),
        migrations.AddField(
            model_name='person',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='country_of_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_birth', to=settings.CITIES_COUNTRY_MODEL),
        ),
    ]
