# Generated by Django 2.0.5 on 2018-09-09 18:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0040_auto_20180905_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alt_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='utterance',
            name='speaker_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.RoleType'),
        ),
    ]
