# Generated by Django 2.0.5 on 2018-10-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0042_auto_20180909_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlperiod',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='parlperiod',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
