# Generated by Django 2.0.5 on 2018-10-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0031_merge_20180523_1452'),
        ('parliament', '0043_auto_20181019_2228'),
    ]

    operations = [
    ]
