# Generated by Django 2.1.2 on 2019-02-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0265_query_wos_db'),
        ('parliament', '0045_search_parliament'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoping.Project'),
        ),
    ]
