# Generated by Django 2.1.2 on 2019-03-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0046_search_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Region'),
        ),
        migrations.AlterField(
            model_name='partylist',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Region'),
        ),
        migrations.AlterField(
            model_name='person',
            name='active_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_active', to=settings.CITIES_COUNTRY_MODEL, verbose_name='Country in which the person is active in politics'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country_of_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_birth', to=settings.CITIES_COUNTRY_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parliament.Party'),
        ),
        migrations.AlterField(
            model_name='search',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Query Creator'),
        ),
        migrations.AlterField(
            model_name='search',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Party'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Constituency'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.Party'),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parliament.Person'),
        ),
    ]
