# Generated by Django 2.2 on 2019-05-28 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0047_auto_20190329_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of entry creation'),
            preserve_default=False,
        ),
    ]
