# Generated by Django 2.2 on 2019-06-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0049_auto_20190528_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Document')),
            ],
        ),
        migrations.AddField(
            model_name='utterance',
            name='agenda_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parliament.AgendaItem'),
        ),
    ]
