# Generated by Django 2.2 on 2019-07-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0050_auto_20190612_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='agenda_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.AgendaItem'),
        ),
    ]
