# Generated by Django 2.2 on 2019-12-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0052_auto_20191015_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interjection',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(null=True)),
                ('resignation_date', models.DateField(null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parliament.Party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parliament.Person')),
            ],
        ),
    ]
