# Generated by Django 2.2 on 2019-12-10 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0053_auto_20191210_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymembership',
            name='period_unknown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partymembership',
            name='entry_date',
            field=models.DateField(default=datetime.date(1700, 1, 1)),
        ),
        migrations.AlterField(
            model_name='partymembership',
            name='resignation_date',
            field=models.DateField(default=datetime.date(2100, 1, 1)),
        ),
    ]
