# Generated by Django 2.2 on 2020-02-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0054_auto_20191210_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.Party'),
        ),
    ]
