# Generated by Django 4.2 on 2023-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0055_auto_20200206_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='has_coal',
            field=models.BooleanField(null=True),
        ),
    ]
