# Generated by Django 2.0.5 on 2018-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20180913_1659'),
    ]
