# Generated by Django 2.0.5 on 2018-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_status_retweeted_by'),
    ]
