# Generated by Django 2.1.2 on 2018-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20180917_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittersearch',
            name='since',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twittersearch',
            name='until',
            field=models.DateTimeField(null=True),
        ),
    ]
