# Generated by Django 2.0.5 on 2018-09-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20180917_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites_count',
            new_name='favourites_count',
        ),
    ]
