# Generated by Django 2.1.2 on 2018-11-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20181030_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites_count',
            new_name='favourites_count',
        ),
    ]
