# Generated by Django 2.1.2 on 2018-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20181113_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='source',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
