# Generated by Django 2.1.2 on 2018-11-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_auto_20181113_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person',
        ),
    ]
