# Generated by Django 2.2 on 2019-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0017_auto_20190215_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField(null=True)),
                ('search_date', models.DateTimeField(null=True)),
                ('user_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
