# Generated by Django 2.2.2 on 2020-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0019_status_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterbasemodel',
            name='lang',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
