# Generated by Django 2.2.9 on 2020-02-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0020_auto_20200115_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittersearch',
            name='search_since',
            field=models.DateTimeField(null=True),
        ),
    ]
