# Generated by Django 2.2.9 on 2020-02-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0021_auto_20200214_1232'),
        ('twitter', '0022_auto_20200210_1542'),
    ]

    operations = [
    ]
