# Generated by Django 2.2.9 on 2021-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0023_merge_20200224_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittersearch',
            name='search_fullapi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twittersearch',
            name='search_until',
            field=models.DateTimeField(null=True),
        ),
    ]
