# Generated by Django 4.2 on 2023-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0024_auto_20210616_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='contributors',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='coordinates',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='geo',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='place',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='twitterbasemodel',
            name='entities',
            field=models.JSONField(null=True),
        ),
    ]
